spring.application.name=videoStreaming
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/video-streaming
spring.datasource.username=postgres
spring.datasource.password=yash+postgressql

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashj001122@gmail.com
spring.mail.password=vrqb yomc ghqp larm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
